### PR TITLE
k8s ListServices, GetService & GetPlan implementation

### PR DESCRIPTION
**Pull request by MHBauer**
not quite copy and paste, but not quite unique either.

also some changes to storage so I store the full structs instead of the limited definition.

### CODE REVIEW

**Comment by duglin** [comment]
When I start the service controller I see this:
```
$ ./service_controller --backend=k8s
 root host is: http://localhost:8080/apis/cncf.org/v1alpha1/namespaces/default/servicebrokers
encoded bytes: {"metadata":{"name":"service-broker.cncf.org"},"apiVersion":"extensions/v1beta1","versions":[{"name":"v1alpha1"}]}

result: &{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[286]] 0xc8200c8100 286 [] false map[] 0xc8200c0000 <nil>}
Error creating k8s TPR [%!s(<nil>)]...
&{409 Conflict 409 HTTP/1.1 1 1 map[Content-Length:[286] Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT]] 0xc8200c8100 286 [] false map[] 0xc8200c0000 <nil>}
encoded bytes: {"metadata":{"name":"sbservice.cncf.org"},"apiVersion":"extensions/v1beta1","versions":[{"name":"v1alpha1"}]}

result: &{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[276]] 0xc8200c84c0 276 [] false map[] 0xc8200f8000 <nil>}
Error creating k8s TPR [%!s(<nil>)]...
&{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[276]] 0xc8200c84c0 276 [] false map[] 0xc8200f8000 <nil>}
encoded bytes: {"metadata":{"name":"service-plan.cncf.org"},"apiVersion":"extensions/v1beta1","versions":[{"name":"v1alpha1"}]}

result: &{409 Conflict 409 HTTP/1.1 1 1 map[Content-Length:[282] Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT]] 0xc820016800 282 [] false map[] 0xc8200f80e0 <nil>}
Error creating k8s TPR [%!s(<nil>)]...
&{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[282]] 0xc820016800 282 [] false map[] 0xc8200f80e0 <nil>}
encoded bytes: {"metadata":{"name":"service-binding.cncf.org"},"apiVersion":"extensions/v1beta1","versions":[{"name":"v1alpha1"}]}

result: &{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[288]] 0xc820016b00 288 [] false map[] 0xc8200c00e0 <nil>}
Error creating k8s TPR [%!s(<nil>)]...
&{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[288]] 0xc820016b00 288 [] false map[] 0xc8200c00e0 <nil>}
encoded bytes: {"metadata":{"name":"service-instance.cncf.org"},"apiVersion":"extensions/v1beta1","versions":[{"name":"v1alpha1"}]}

result: &{409 Conflict 409 HTTP/1.1 1 1 map[Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[290] Content-Type:[application/json]] 0xc8200c8980 290 [] false map[] 0xc8200c01c0 <nil>}
Error creating k8s TPR [%!s(<nil>)]...
&{409 Conflict 409 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 10:03:20 GMT] Content-Length:[290]] 0xc8200c8980 290 [] false map[] 0xc8200c01c0 <nil>}
Service Controller started on port 10000
```

Are all of the 409's expected given the current state of things?

**Comment by MHBauer** [comment]
Only if you've started it more than once.

**Comment by duglin** [comment]
ok, so before each run I need to erase all TPRs?  Can we fix that?

**Comment by duglin** [comment]
When I try to create a SB, I get this:
```
&{freePlan ffffffff-0000-0000-0000-000000000000 free is good <nil> true {{ } { }} 12345678-abcd-1234-bcde-1234567890ab} ffffffff-0000-0000-0000-000000000000
sending: {"name":"freePlan","id":"ffffffff-0000-0000-0000-000000000000","description":"free is good","free":true,"schemas":{"instance":{"inputs":"","outputs":""},"binding":{"inputs":"","outputs":""}},"Service":"12345678-abcd-1234-bcde-1234567890ab","apiVersion":"cncf.org/v1alpha1","kind":"ServicePlan","metadata":{"name":"ffffffff-0000-0000-0000-000000000000"}}

 to http://%v/apis/cncf.org/v1alpha1/namespaces/default/serviceplans
Error creating k8s service TPR [%!s(<nil>)]...
&{404 Not Found 404 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Tue, 20 Sep 2016 12:33:13 GMT] Content-Length:[174]] 0xc8200d2d40 174 [] false map[] 0xc8200c0a80 <nil>}
```

**Comment by MHBauer** [comment]
I do not see that.

What version of k8s and what service broker?

**Comment by duglin** [comment]
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

I'm using the SB from our git repo.

With this command: `sc brokers create test http://localhost:9090`

**Comment by MHBauer** [comment]
Do TPRs work in 1.3? I didn't think all the fixes were in until 1.4. 

I've done the same with a gobroker and a nodebroker. I can then list the brokers and the inventory.

**Comment by MHBauer** [comment]
adding
```
sending: {"id":"801d6116-de8a-4446-ab24-3bbbf6365195","name":"SampleAsyncService","description":"Sample Async Service Broker","bindable":true,"plan_updateable":true,"tags":["tag1a","tag1b"],"requires":null,"dashboard_client":{"id":"SampleAsyncServiceBroker","redirect_uri":"http://127.0.0.1:3000/sso_dashboard","secret":"SampleAsyncServiceBrokerSecret"},"ServiceBroker":"1c1f8fef-03ac-4a99-b272-286236b429c9","plans":["ac7c234e-e4d8-4821-a7b8-5f2838ac3263","e1c457ac-6f14-4784-878c-d7f3d8950e71","9e613d91-da80-4e40-87af-87d791e351ba","32ca73db-6d95-4cea-bba8-f69b2781d201","b1ab7949-2fee-43b1-ac6d-93679a31261f","4fed6abc-f26b-4cc3-971f-0b210da2dfba"],"Instances":null,"apiVersion":"cncf.org/v1alpha1","kind":"Sbservice","metadata":{"name":"801d6116-de8a-4446-ab24-3bbbf6365195"}}

 to http://%v/apis/cncf.org/v1alpha1/namespaces/default/sbservicesadding broker to k8s &{1c1f8fef-03ac-4a99-b272-286236b429c9 sasb http://127.0.0.1:3000 SampleAsyncServiceBrokerUser SampleAsyncServiceBrokerPassword 1474375123 0 /v2/service_brokers/1c1f8fef-03ac-4a99-b272-286236b429c9 [801d6116-de8a-4446-ab24-3bbbf6365195]}
sending: {"ID":"1c1f8fef-03ac-4a99-b272-286236b429c9","Name":"sasb","BrokerURL":"http://127.0.0.1:3000","AuthUsername":"SampleAsyncServiceBrokerUser","AuthPassword":"SampleAsyncServiceBrokerPassword","Created":"1474375123","Updated":0,"SelfURL":"/v2/service_brokers/1c1f8fef-03ac-4a99-b272-286236b429c9","Services":["801d6116-de8a-4446-ab24-3bbbf6365195"],"apiVersion":"cncf.org/v1alpha1","kind":"ServiceBroker","metadata":{"name":"1c1f8fef-03ac-4a99-b272-286236b429c9"}}
&{freePlan ffffffff-0000-0000-0000-000000000000 free is good <nil> true {{ } { }} 12345678-abcd-1234-bcde-1234567890ab} ffffffff-0000-0000-0000-000000000000
sending: {"name":"freePlan","id":"ffffffff-0000-0000-0000-000000000000","description":"free is good","free":true,"schemas":{"instance":{"inputs":"","outputs":""},"binding":{"inputs":"","outputs":""}},"Service":"12345678-abcd-1234-bcde-1234567890ab","apiVersion":"cncf.org/v1alpha1","kind":"ServicePlan","metadata":{"name":"ffffffff-0000-0000-0000-000000000000"}}

 to http://%v/apis/cncf.org/v1alpha1/namespaces/default/serviceplans
&{costlyPlan eeeeeeee-1111-1111-1111-111111111111 not so free <nil> false {{ } { }} 12345678-abcd-1234-bcde-1234567890ab} eeeeeeee-1111-1111-1111-111111111111
sending: {"name":"costlyPlan","id":"eeeeeeee-1111-1111-1111-111111111111","description":"not so free","free":false,"schemas":{"instance":{"inputs":"","outputs":""},"binding":{"inputs":"","outputs":""}},"Service":"12345678-abcd-1234-bcde-1234567890ab","apiVersion":"cncf.org/v1alpha1","kind":"ServicePlan","metadata":{"name":"eeeeeeee-1111-1111-1111-111111111111"}}

 to http://%v/apis/cncf.org/v1alpha1/namespaces/default/serviceplans
&{12345678-abcd-1234-bcde-1234567890ab myService1 very cool true false [] [] <nil> <nil> c57b0c71-959f-4592-849b-8f8ea716b35d [ffffffff-0000-0000-0000-000000000000 eeeeeeee-1111-1111-1111-111111111111] map[]} 12345678-abcd-1234-bcde-1234567890ab
sending: {"id":"12345678-abcd-1234-bcde-1234567890ab","name":"myService1","description":"very cool","bindable":true,"plan_updateable":false,"tags":null,"requires":null,"dashboard_client":null,"ServiceBroker":"c57b0c71-959f-4592-849b-8f8ea716b35d","plans":["ffffffff-0000-0000-0000-000000000000","eeeeeeee-1111-1111-1111-111111111111"],"Instances":null,"apiVersion":"cncf.org/v1alpha1","kind":"Sbservice","metadata":{"name":"12345678-abcd-1234-bcde-1234567890ab"}}

 to http://%v/apis/cncf.org/v1alpha1/namespaces/default/sbservicesadding broker to k8s &{c57b0c71-959f-4592-849b-8f8ea716b35d gocrap http://127.0.0.1:9090   1474375170 0 /v2/service_brokers/c57b0c71-959f-4592-849b-8f8ea716b35d [12345678-abcd-1234-bcde-1234567890ab]}
sending: {"ID":"c57b0c71-959f-4592-849b-8f8ea716b35d","Name":"gocrap","BrokerURL":"http://127.0.0.1:9090","AuthUsername":"","AuthPassword":"","Created":"1474375170","Updated":0,"SelfURL":"/v2/service_brokers/c57b0c71-959f-4592-849b-8f8ea716b35d","Services":["12345678-abcd-1234-bcde-1234567890ab"],"apiVersion":"cncf.org/v1alpha1","kind":"ServiceBroker","metadata":{"name":"c57b0c71-959f-4592-849b-8f8ea716b35d"}}
```

listing
```
listing all brokers
Got 2 brokers.
uri is: http://localhost:8080/apis/cncf.org/v1alpha1/namespaces/default/servicebrokers/1c1f8fef-03ac-4a99-b272-286236b429c9
returned json: {ServiceBroker:0xc4200f0b40 ApiVersion:cncf.org/v1alpha1 Kind:ServiceBroker Metadata:{Name:1c1f8fef-03ac-4a99-b272-286236b429c9}}
uri is: http://localhost:8080/apis/cncf.org/v1alpha1/namespaces/default/servicebrokers/c57b0c71-959f-4592-849b-8f8ea716b35d
returned json: {ServiceBroker:0xc420238480 ApiVersion:cncf.org/v1alpha1 Kind:ServiceBroker Metadata:{Name:c57b0c71-959f-4592-849b-8f8ea716b35d}}
Inventory
listing all services
Got 2 services.
service 0 &{0xc4200fe540 cncf.org/v1alpha1 Sbservice {12345678-abcd-1234-bcde-1234567890ab}}
service 1 &{0xc4200fe600 cncf.org/v1alpha1 Sbservice {801d6116-de8a-4446-ab24-3bbbf6365195}}
getting a single service
Got a service! {0xc42023c180 cncf.org/v1alpha1 Sbservice {12345678-abcd-1234-bcde-1234567890ab}}
getting a single plan
Got a plan! &{0xc4200eb540 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc420106a00 cncf.org/v1alpha1 ServicePlan {ffffffff-0000-0000-0000-000000000000}}
getting a single plan
Got a plan! &{0xc4201129c0 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc42025c280 cncf.org/v1alpha1 ServicePlan {eeeeeeee-1111-1111-1111-111111111111}}
getting a single service
Got a service! {0xc4200fe6c0 cncf.org/v1alpha1 Sbservice {801d6116-de8a-4446-ab24-3bbbf6365195}}
getting a single plan
Got a plan! &{0xc420112b00 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc42025c3c0 cncf.org/v1alpha1 ServicePlan {ac7c234e-e4d8-4821-a7b8-5f2838ac3263}}
getting a single plan
Got a plan! &{0xc4200eb800 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc420106aa0 cncf.org/v1alpha1 ServicePlan {e1c457ac-6f14-4784-878c-d7f3d8950e71}}
getting a single plan
Got a plan! &{0xc420112c40 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc42025c460 cncf.org/v1alpha1 ServicePlan {9e613d91-da80-4e40-87af-87d791e351ba}}
getting a single plan
Got a plan! &{0xc4200eb940 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc420106b40 cncf.org/v1alpha1 ServicePlan {32ca73db-6d95-4cea-bba8-f69b2781d201}}
getting a single plan
Got a plan! &{0xc420112d80 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc42025c500 cncf.org/v1alpha1 ServicePlan {b1ab7949-2fee-43b1-ac6d-93679a31261f}}
getting a single plan
Got a plan! &{0xc4200eba80 {0 0} false 0xc420010170 <nil> 0x5222e0} {0xc420106be0 cncf.org/v1alpha1 ServicePlan {4fed6abc-f26b-4cc3-971f-0b210da2dfba}}
```

I'll try the gobroker by itself after a restart.

**Comment by MHBauer** [comment]
cli side
```
root@masterbuilder:~/go/src/github.com/servicebroker/servicebroker/cli# ./sc brokers create gocrap http://127.0.0.1:9090
entity:
  auth_username: ""
  broker_url: http://127.0.0.1:9090
  name: gocrap
metadata:
  created_at: "2016-09-20T12:49:15Z"
  guid: 5990e874-0871-4600-a4da-04312dcd619b
  url: /v2/service_brokers/5990e874-0871-4600-a4da-04312dcd619b

root@masterbuilder:~/go/src/github.com/servicebroker/servicebroker/cli# ./sc brokers list
- AuthPassword: ""
  AuthUsername: ""
  BrokerURL: http://127.0.0.1:9090
  Created: "1474375755"
  GUID: 5990e874-0871-4600-a4da-04312dcd619b
  Name: gocrap
  SelfURL: /v2/service_brokers/5990e874-0871-4600-a4da-04312dcd619b
  Updated: 0

root@masterbuilder:~/go/src/github.com/servicebroker/servicebroker/cli# ./sc inventory
service              plans                     description
myService1           freePlan,costlyPlan       very cool
```

**Comment by MHBauer** [comment]
How would I make sure to do the cleanup at the end? I'm not sure what go feature to hook into.

If we do cleanup then we'll need a flag to control that behavior. I think the default behavior should be to leave everything defined, as k8s storage is our persistence layer.

If you can, please try a k8s server build of 1.4+. I am not sure all of the TPR fixes are in 1.3.

**Comment by duglin** [comment]
I wasn't suggesting we delete stuff, rather check if the TPR is defined before we try to define it again. Assuming that's the cause of the 409.

**Comment by MHBauer** [comment]
sure. write up an issue. at the moment it's just easier to attempt to redefine it and ignore the error.

**Comment by MHBauer** [comment]
What else @duglin?

**Comment by duglin** [comment]
LGTM

**Pull request merged**
